var annotated_dup =
[
    [ "ControlTaskParameters_", "struct_control_task_parameters__.html", null ],
    [ "corCoRoutineControlBlock", "structcor_co_routine_control_block.html", null ],
    [ "EventGroupDef_t", "struct_event_group_def__t.html", null ],
    [ "gpioDigitalPinSetup_", "structgpio_digital_pin_setup__.html", null ],
    [ "GptmCoreState_", "struct_gptm_core_state__.html", null ],
    [ "HalGptmCompare16BitMode", "struct_hal_gptm_compare16_bit_mode.html", null ],
    [ "HeapRegion", "struct_heap_region.html", null ],
    [ "QueueDefinition", "struct_queue_definition.html", null ],
    [ "QueuePointers", "struct_queue_pointers.html", null ],
    [ "SemaphoreData", "struct_semaphore_data.html", null ],
    [ "StreamBufferDef_t", "struct_stream_buffer_def__t.html", null ],
    [ "SysctlCpuFreqSetup_", "struct_sysctl_cpu_freq_setup__.html", null ],
    [ "tskTaskControlBlock", "structtsk_task_control_block.html", null ],
    [ "xLIST", "structx_l_i_s_t.html", null ],
    [ "xLIST_ITEM", "structx_l_i_s_t___i_t_e_m.html", null ],
    [ "xMEMORY_REGION", "structx_m_e_m_o_r_y___r_e_g_i_o_n.html", null ],
    [ "xMINI_LIST_ITEM", "structx_m_i_n_i___l_i_s_t___i_t_e_m.html", null ],
    [ "xSTATIC_EVENT_GROUP", "structx_s_t_a_t_i_c___e_v_e_n_t___g_r_o_u_p.html", null ],
    [ "xSTATIC_LIST", "structx_s_t_a_t_i_c___l_i_s_t.html", null ],
    [ "xSTATIC_LIST_ITEM", "structx_s_t_a_t_i_c___l_i_s_t___i_t_e_m.html", null ],
    [ "xSTATIC_MINI_LIST_ITEM", "structx_s_t_a_t_i_c___m_i_n_i___l_i_s_t___i_t_e_m.html", null ],
    [ "xSTATIC_QUEUE", "structx_s_t_a_t_i_c___q_u_e_u_e.html", null ],
    [ "xSTATIC_STREAM_BUFFER", "structx_s_t_a_t_i_c___s_t_r_e_a_m___b_u_f_f_e_r.html", null ],
    [ "xSTATIC_TCB", "structx_s_t_a_t_i_c___t_c_b.html", null ],
    [ "xSTATIC_TIMER", "structx_s_t_a_t_i_c___t_i_m_e_r.html", null ],
    [ "xTASK_PARAMETERS", "structx_t_a_s_k___p_a_r_a_m_e_t_e_r_s.html", null ],
    [ "xTASK_STATUS", "structx_t_a_s_k___s_t_a_t_u_s.html", null ],
    [ "xTIME_OUT", "structx_t_i_m_e___o_u_t.html", null ]
];