/*
 * paramsGptmPinoutsNames.h
 *
 *  Created on: 07.04.2022
 *
 */

#ifndef PARAMS_GPTM_PARAMS_GPTM_PARAMSGPTMPINOUTSNAMES_H_
#define PARAMS_GPTM_PARAMS_GPTM_PARAMSGPTMPINOUTSNAMES_H_

enum ParamsGptmPinout {
    paramsUart2RxPD4TxPD5 = 0
};


#endif /* PARAMS_GPTM_PARAMS_GPTM_PARAMSGPTMPINOUTSNAMES_H_ */
